name: Install dependencies
author: arpitBhalla
description: ''
inputs:
  install_website:
    description: 'If true, install website dependencies.'
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Cache root dependencies
      uses: actions/cache@v3
      id: root_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-rne-cache-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-rne-cache-${{ hashFiles('yarn.lock') }}

    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Enable Yarn with Corepack
      run: corepack prepare yarn@stable --activate
      shell: bash

    - name: Install root dependencies
      if: steps.root_cache.outputs.cache-hit != 'true'
      run: yarn install
      shell: bash

    - name: Cache website dependencies
      uses: actions/cache@v3
      if: inputs.install_website == 'true'
      id: website_cache
      with:
        path: website/node_modules
        key: ${{ runner.os }}-rne-website-${{ hashFiles('website/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-rne-website-${{ hashFiles('website/yarn.lock') }}

    - name: Install website dependencies
      if: steps.website_cache.outputs.cache-hit != 'true' && inputs.install_website == 'true'
      run: yarn install
      working-directory: website
      shell: bash
