name: docs
on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # avoid using GITHUB_TOKEN for push
          fetch-depth: 0 # fetch all history to allow pushing refs to dest repo

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Enable Yarn with Corepack
        run: corepack prepare yarn@stable --activate
        shell: bash

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          install_website: true

      - name: Build 🔧
        run: yarn docs-build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: 'React Native vElements CI'
          user_email: 'react-native-elements-ci@users.noreply.github.com'
          cname: https://thevikalpui.netlify.app
